### ISSUE TITLE
Can't turn off debug

### ISSUE THREAD

**Issue by andrewspode** [loeken/cryptocompare-api-php-wrapper#2]
I'm not sure if I'm doing something wrong here - but I can't seem to turn off debug, so I always get the URI output.

`$cryptocompareApi = new Cryptocompare\CryptocompareApi();
$cryptocompareApi->debug = false;
`

If I print_r($cryptocompareApi) it shows as modified - but at the try/catch block if I check what $this->debug is, it's still set to true. 

I've not done a lot of OO in PHP, and I'm also using PHP7 which has made some changes - so not sure If I'm doing something wrong. From memory, I thought this sort of stuff is usually done in a construct function, or at least using a getter/setter function.

**Comment by loeken** [comment]
I guess that was fixed by your pull request?

**Comment by andrewspode** [comment]
Not as far as I know. I couldn't get to the bottom of it.

**Comment by loeken** [comment]
Okey i think i see where you problem lies :)

I just pushed a small change: https://github.com/loeken/cryptocompare-api-php-wrapper/commit/317527b8cff2d8913af661ea6eaa2e3db32e8ab9

Now debug is set to false, and i created a constructor where you can pass true as param to enable debugging, let me know if that`s what you were looking for.

**Comment by andrewspode** [comment]
I think that should do the trick! For my own sanity - was I doing anything wrong?

**Comment by loeken** [comment]
good to hear,
not really sure if i can tell you what you did wrong, your pull request fixed the == true issue 
+            if ($this->debug == true ) { 

so I tested doing the  $cryptocompareApi->debug = false like you described initially and it did work, tested on  PHP 7.0.22-0ubuntu0.16.04.1 (fpm-fcgi).

If thats all, feel free to close this issue :)
