### ISSUE TITLE
Why i'am getting list of news providers with getNews() function instead of news?

### ISSUE THREAD

**Issue by monikamni** [loeken/cryptocompare-api-php-wrapper#4]

**Comment by loeken** [comment]
fixed in https://github.com/loeken/cryptocompare-api-php-wrapper/commit/76ffb64d9a8101575a0ebbd8daa4f88fc87ce645 let me know if it works i think i only had the wrong path in there

**Comment by loeken** [comment]
feel free to reopen or create new one if your problem wasnt solved :)
