### ISSUE TITLE
error: tsyms param seems to be missing

### ISSUE THREAD

**Issue by nuryagdym** [loeken/cryptocompare-api-php-wrapper#6]
This code in documentation causing
`$cryptocomparePrice = new Cryptocompare\Price();
$response = $cryptocomparePrice->getSinglePrice("1", "BTC", array("USD", 'EUR'), "CCCAGG", "false");`

Error: tsyms param seems to be missing

I tried to implode tsyms and then it did work:
`$response = $cryptocomparePrice->getSinglePrice("1", "BTC", implode(',', array('USD', 'EUR')), "CCCAGG", "false");`

**Comment by loeken** [comment]
this should be solved with the new version i pushed last night
