### ISSUE TITLE
tryConversion should be a boolean value

### ISSUE THREAD

**Issue by nuryagdym** [loeken/cryptocompare-api-php-wrapper#7]
I get this error this week. last week there was not any problem.
To fix problem:
tryConversion values should be 
tryConversion = 'true';
tryConversion = 'false';
instead of
tryConversion = '1';
tryConversion = '0';

**Comment by loeken** [comment]
fixed in https://github.com/loeken/cryptocompare-api-php-wrapper/commit/ae0737cfb54a8705d85d67625fef1c08614751dd
